#!/bin/bash

readonly KSAU_VERSION=251
readonly KSAU_RELEASE_TYPE=stable
readonly KSAU_VERSION_STRING="Version 2.5.1 (Stable)"

#Define colors
normal=$(echo -en "\e[0m")
orange=$(echo -en "\e[33m")
aqua=$(echo -en "\e[36m")
lightgreen=$(echo -en "\e[92m")
Normal='\033[0m'
Black='\033[0;30m'  # Black
Red=$'\033[0;31m'   # Red
Green='\033[0;32m'  # Green
Yellow='\033[0;33m' # Yellow
Blue='\033[0;34m'   # Blue
Purple='\033[0;35m' # Purple
Cyan='\033[0;36m'   # Cyan
White='\033[0;37m'  # White

UPLINE=$(tput cuu1)
CLEARLINE=$(tput el)

set -o pipefail
readonly status_dir="$(mktemp -d)"

trap "rm -rf $status_dir" EXIT

upline() {
    for _ in $(seq $1); do
        echo -ne "$UPLINE"
    done
}

clearline() {
    echo -ne "$CLEARLINE"
}

dependencies() {
    if declare -p TERMUX_VERSION &>/dev/null; then
        echo "Starting Installation...."
        pkg update >/dev/null 2>&1
        pkg install rclone jq -y >/dev/null 2>&1
        echo ""
        echo "${orange}Installation Completed. ${normal}"
        return
    fi

    echo ""
    echo "Make sure you have sudo privilages"
    echo "This will only work for Linux/macOS/BSD systems."
    echo ""
    sudo curl https://rclone.org/install.sh 2>/dev/null | sudo bash >/dev/null 2>&1
    echo ""
    echo "${orange}Please install jq manually, No script found"
    echo "Possibly with 
			${aqua}sudo apt-get install jq ${normal}OR
			${aqua}sudo pacman -S jq ${normal}OR
			${aqua}sudo dnf install jq ${normal}OR
			${aqua}sudo zypper install jq ${normal}OR
			${aqua}apk add jq ${normal}OR
			${aqua}pkg install jq${normal}"
    echo ''
}

setup() {
    mkdir -p ~/.config/rclone
    rm ~/.config/rclone/rclone.conf >/dev/null 2>&1
    if ! command -v wget &>/dev/null; then
        echo "${aqua}Does this machine even have simple pkgs installed?"
        echo "Please install ${orange}wget ${aqua}manually and continue...${normal}"
        exit
    fi
    wget https://gist.githubusercontent.com/ksauraj/cf531848e0d849296406d38a98b2a544/raw/rclone.conf >/dev/null 2>&1
    mv rclone.conf ~/.config/rclone
    if ! command -v rclone &>/dev/null; then
        echo "${aqua}Dependencies not found. Make sure to proceed with the command 'ksau dependencies'"
        echo "${aqua}OR manually install ${orange}rclone ${aqua}and ${orange}jq${normal}"
        exit
    else
        if ! command -v jq &>/dev/null; then
            echo "${aqua}Dependencies not found. Make sure to proceed with the command 'ksau dependencies'"
            echo "${aqua}Please install jq manually, No script found"
            echo "Possibly with
					${aqua}sudo apt-get install jq ${normal}OR
					${aqua}sudo pacman -S jq ${normal}OR
					${aqua}sudo dnf install jq ${normal}OR
					${aqua}sudo zypper install jq ${normal}OR
					${aqua}apk add jq ${normal}OR
					${aqua}pkg install jq${normal}"
            exit
        fi
    fi
    echo "Setup Completed"
}

# Generates new filename with random strings at last (before extension if present).
# new name for 'myfile.txt' -> 'myfile-78e11b8c.txt'
# new name for 'myfile' -> 'myfile-78e11b8c'
add_random_string() {
    local filename="$1"
    local extension="${filename##*.}"
    local name="${filename%.*}"
    local random_string="$(date +%s | sha256sum | base64 | head -c 8)"
    if [ -z "$extension" ]; then
        new_filename="$name-$random_string"
    else
        new_filename="$name-$random_string.$extension"
    fi
}

# Simple progressbar animation.
# Usage : progress_bar ${percentage} ${upload_speed} $(eta) ${status}
progress_bar() {
    if [[ ${1} < 10 ]]; then
        echo "${Yellow}Progress ${Green}[=>---------${Cyan}${1}%${Normal}${Green}---------<=]"
    elif [[ ${1} -lt 20 ]]; then
        echo "${Yellow}Progress ${Green}[==>--------${Cyan}${1}%${Normal}${Green}--------<==]"
    elif [[ ${1} -lt 30 ]]; then
        echo "${Yellow}Progress ${Green}[===>-------${Cyan}${1}%${Normal}${Green}-------<===]"
    elif [[ ${1} -lt 40 ]]; then
        echo "${Yellow}Progress ${Green}[====>------${Cyan}${1}%${Normal}${Green}------<====]"
    elif [[ ${1} -lt 50 ]]; then
        echo "${Yellow}Progress ${Green}[=====>-----${Cyan}${1}%${Normal}${Green}-----<=====]"
    elif [[ ${1} -lt 60 ]]; then
        echo "${Yellow}Progress ${Green}[======>----${Cyan}${1}%${Normal}${Green}----<======]"
    elif [[ ${1} -lt 70 ]]; then
        echo "${Yellow}Progress ${Green}[=======>---${Cyan}${1}%${Normal}${Green}---<=======]"
    elif [[ ${1} -lt 80 ]]; then
        echo "${Yellow}Progress ${Green}[========>--${Cyan}${1}%${Normal}${Green}--<========]"
    elif [[ ${1} -lt 90 ]]; then
        echo "${Yellow}Progress ${Green}[=========>-${Cyan}${1}%${Normal}${Green}-<=========]"
    elif [[ ${1} -lt 100 ]]; then
        echo "${Yellow}Progress ${Green}[==========>${Cyan}${1}%${Normal}${Green}<==========]"
    elif [[ ${1} == 100 ]]; then
        echo "${Yellow}Progress ${Green}[===========${Cyan}${1}%${Normal}${Green}===========]"
    fi
}

# Upload file to give folder and use new filename if -r argument was passed and printing out new animation.
rclone_progress_bar() {
    tput civis
    echo "Starting upload..."
    rm -f log
    touch log
    if [ -z "$new_filename" ]; then new_filename=$(basename "$file"); fi
    rclone -P --checkers=32 --onedrive-chunk-size 60M copyto "$file" oned:/"${u_folder}"/"$new_filename" | tee log >/dev/null || touch "$status_dir/failed" &
    until [ -z "$(jobs -r)" ]; do
        if [ -f "$status_dir/failed" ]; then
            echo
            echo "${Red}Upload failed!${Normal}"
            break
        fi
        local percent=$(grep -Eo '[0-9]{1,3}'% log | tail -n1 | cut -d '%' -f 1)
        local ups=$(grep 'ETA' log | tail -n1 | cut -d ',' -f5)
        local eta=$(grep 'ETA' log | tail -n1 | cut -d ',' -f6 | sed 's/ETA //')
        local status=$(grep 'ETA' log | tail -n1 | cut -d ',' -f3 | sed 's/^.*   //')
        progbar=$(progress_bar "$percent")
        echo -e "$(clearline)$progbar
    $(clearline)${Yellow}   UPS:${Normal} $ups
    $(clearline)${Yellow}   ETA:${Normal} $eta
    $(clearline)${Yellow}STATUS:${Normal} $status
$(upline 5)"
    done #|| echo -ne "\rDownload Can't be completed, Check download link." && tput cnorm && exit 1
    tput cnorm
}

# Below function is copied from - https://gist.github.com/jaytaylor/5a90c49e0976aadfe0726a847ce58736
# Credit to @jkishner for https://gist.github.com/jkishner/2fccb24640a27c2d7ac9
function url_encode() {
    builtin echo "$@" |
        sed \
            -e 's/%/%25/g' \
            -e 's/ /%20/g' \
            -e 's/!/%21/g' \
            -e 's/"/%22/g' \
            -e "s/'/%27/g" \
            -e 's/#/%23/g' \
            -e 's/(/%28/g' \
            -e 's/)/%29/g' \
            -e 's/+/%2b/g' \
            -e 's/,/%2c/g' \
            -e 's/-/%2d/g' \
            -e 's/:/%3a/g' \
            -e 's/;/%3b/g' \
            -e 's/?/%3f/g' \
            -e 's/@/%40/g' \
            -e 's/\$/%24/g' \
            -e 's/\&/%26/g' \
            -e 's/\*/%2a/g' \
            -e 's/\./%2e/g' \
            -e 's/\//%2f/g' \
            -e 's/\[/%5b/g' \
            -e 's/\\/%5c/g' \
            -e 's/\]/%5d/g' \
            -e 's/\^/%5e/g' \
            -e 's/_/%5f/g' \
            -e 's/`/%60/g' \
            -e 's/{/%7b/g' \
            -e 's/|/%7c/g' \
            -e 's/}/%7d/g' \
            -e 's/~/%7e/g'
}

# rclone_progress_bar -> progress_bar -> Print dowload link.
upload() {
    if [[ $KSAUOPT_ADD_RAND_STR == true ]]; then
        add_random_string "$(basename "$file")"
    fi
    echo "Initializing process, might take up to 10 seconds..."
    rclone_progress_bar
    wait
    if [ -f "$status_dir/failed" ]; then
        echo -e "\rUpload Failed .......\n"
        exit 1
    fi
    url_file=$(url_encode "${new_filename}")
    url_folder=$(jq -rn --arg x "${u_folder%/}" '$x|@uri')
    echo -e "\n$(clearline)$(upline 1)$(clearline)$(upline 1)"
    echo "$(clearline) Upload Completed "
    echo "$(clearline) Download link - ${lightgreen}https://index.sauraj.eu.org/${url_folder}/${url_file}${normal} "
    echo "$(clearline)"

    if [[ $KSAUOPT_QUIET == true ]]; then
        builtin echo "https://index.sauraj.eu.org/${url_folder}/${url_file}"
    fi
}

help() {
    echo "
${aqua}Usage : ksau [-r] [OPTION]... [FILE]...${normal}

${aqua}Options:${normal}
-r    Add random string to the end of filename (but before extension) when uploading
    -q    Suppress all output, printing only the link after upload is finished

    Note that all options must be passed ${Red}BEFORE${normal} other arguments.

${aqua}upload [-r] [FILE] [FOLDER]${normal}: Uploads the given file to the given folder
                            on index.

${aqua}setup${normal}                     : Recquired while using first time.

${aqua}update${normal}                    : Fetch and install latest version
                            available.

${aqua}dependencies${normal}              : Installs recquired dependencies.

${aqua}help${normal}                      : To get this message.

${aqua}version${normal}                   : To get version info.

Example : ${lightgreen}ksau upload test.txt Public

${orange}Tool By Sauraj (@Ksauraj) and @Hakimi0804${normal}
"
}

_update_copy() {
    local file=$1
    if declare -p TERMUX_VERSION &>/dev/null; then
        cp -f "$file" "$PREFIX/bin/ksau"
        chmod +x "$PREFIX/bin/ksau"
    else
        sudo cp -f "$file" /usr/local/bin/ksau
        chmod +x "/usr/local/bin/ksau"
    fi
    echo "Updated ksau copied."
}

update() {
    if ! ping -c2 google.com &>/dev/null; then
        echo "Please check your internet connection"
        return
    fi

    local tmpfilename new_version new_version_string
    tmpfilename=ksau-$RANDOM

    echo "Fetching"
    curl --progress-bar -Lo "$tmpfilename" https://raw.githubusercontent.com/ksauraj/global_index_source/master/ksau

    new_version=$(grep 'KSAU_VERSION=' "$tmpfilename" | head -n1 | cut -d= -f2)
    new_version_string=$(grep 'KSAU_VERSION_STRING=' "$tmpfilename" | head -n1 | cut -d= -f2)
    if [[ $new_version -gt $KSAU_VERSION ]]; then
        echo -e "New version found $Cyan($KSAU_VERSION_STRING -> $new_version_string)$Normal"
        _update_copy "$tmpfilename"
    else
        echo "Already on latest release."
    fi

    rm -f "$tmpfilename"
}

version() {
    echo "${orange}${KSAU_VERSION_STRING} ${normal}"
}

KSAUOPT_ADD_RAND_STR=false
KSAUOPT_QUIET=false

while getopts "rq" opt; do
    case $opt in
    r)
        KSAUOPT_ADD_RAND_STR=true
        ;;
    q)
        KSAUOPT_QUIET=true
        # Override all echo call.
        echo() { true; }
        ;;
    ?)
        # Getopts already print error for us so just exit
        exit 1
        ;;
    esac
done

# Remove all args parsed by getopts
shift $((OPTIND - 1))

if [[ $1 == "upload" ]]; then
    readonly file="$2"
    readonly u_folder="$3"
    upload
elif [[ $1 == "setup" ]]; then
    setup
elif [[ $1 == "dependencies" ]]; then
    dependencies
elif [[ $1 == "update" ]]; then
    update
elif [[ $1 == "version" ]]; then
    version
elif [[ $1 == "help" ]]; then
    help
elif [[ $1 == "" ]]; then
    help
else
    echo "Unknown Argument passed."
    help
fi
