#!/bin/bash

#Define colors
normal=$(echo -en "\e[0m")
orange=$(echo -en "\e[33m")
aqua=$(echo -en "\e[36m")
lightgreen=$(echo -en "\e[92m")

if declare -p TERMUX_VERSION &>/dev/null; then
    SUDO=""
    INSTALLDIR=$PREFIX/bin/ksau
else
    SUDO=sudo
    INSTALLDIR=/usr/local/bin/ksau
    echo "Make sure you have sudo privileges"
fi

rm ksau >/dev/null 2>&1
$SUDO rm $INSTALLDIR >/dev/null 2>&1
curl https://raw.githubusercontent.com/noobyysauraj/global_index_source/master/ksau >ksau 2>/dev/null
$SUDO mv ksau $INSTALLDIR
chmod +x $INSTALLDIR

if ! command -v ksau &>/dev/null; then
    echo "${orange}Installation Failed !!!"
    echo "Posssible Solution : Don't run as root or check Root version.${normal}"
    exit
else
    ksau
fi
